config/routes.rb
Mj::Application.routes.draw do


  resources :services


  resources :socials


  resources :gender_notifications


  root :to => redirect('/about')

  get "about/aboutus"

  captcha_route

  resources :posts


  # root :to => "home#index"
  
  # get "home/index"


  # get "home/aboutus"
  # root :to => redirect('/aboutus')

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :videos

 
 
  resources :ads


  resources :relatives
  resources :mappings
  resources :mapping_relations
  resources :feedbacks
  resources :relations
  resources :family_members
  resources :users
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "mjnews" => "posts#index", :as => "posts"



  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "signup" => "users#sign_up", :as => "signup"
  get '/ads/:id/sai', to: 'ads#sai'
  get "search" => "users#index", :as => "search"
  get "log" => "users#search", :as => "log"
  get "slog" => "services#servicelog", :as => "slog"
  get "products" => "ads#products", :as => "products"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "tc" => "home#tc" , :as => "tc"


 
   get "privacy" => "home#privacy" , :as => "privacy"

  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  # get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  # root :to => "users#home" # "advertisements"
  match ':controller(/:action(/:id))(.:format)'
end

app/models/relative.rb
class Relative < ActiveRecord::Base
  attr_accessible :existing_member_id, :flag, :new_member_id, :present_id, :relationship, :accept_request, :reverse_relationship, :reverse_flag, :reverse_accept_request
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  # GET /relatives
  # GET /relatives.json
  def index
    @relatives = Relative.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relatives }
    end
  end

  # GET /relatives/1
  # GET /relatives/1.json
  def show
    @relative = Relative.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relative }
    end
  end

  # GET /relatives/new
  # GET /relatives/new.json
  def new
    @relative = Relative.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relative }
    end
  end

  # GET /relatives/1/edit
  def edit
    @relative = Relative.find(params[:id])
  end

  # POST /relatives
  # POST /relatives.json
  def create
    @relative = Relative.new(params[:relative])

    respond_to do |format|
      if @relative.save
        format.html { redirect_to @relative, notice: 'Relative was successfully created.' }
        format.json { render json: @relative, status: :created, location: @relative }
      else
        format.html { render action: "new" }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relatives/1
  # PUT /relatives/1.json
  def update
    @relative = Relative.find(params[:id])

    respond_to do |format|
      if @relative.update_attributes(params[:relative])
        format.html { redirect_to @relative, notice: 'Relative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatives/1
  # DELETE /relatives/1.json
  def destroy
    @relative = Relative.find(params[:id])
    @relative.destroy

    respond_to do |format|
      format.html { redirect_to relatives_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/relatives/_form.html.erb
<%= form_for(@relative) do |f| %>
  <% if @relative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relative.errors.count, "error") %> prohibited this relative from being saved:</h2>

      <ul>
      <% @relative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :present_id %><br />
    <%= f.number_field :present_id %>
  </div>
  <div class="field">
    <%= f.label :existing_member_id %><br />
    <%= f.number_field :existing_member_id %>
  </div>
  <div class="field">
    <%= f.label :new_member_id %><br />
    <%= f.number_field :new_member_id %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :flag %><br />
    <%= f.check_box :flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relatives/edit.html.erb
<h1>Editing relative</h1>

<%= render 'form' %>

<%= link_to 'Show', @relative %> |
<%= link_to 'Back', relatives_path %>

app/views/relatives/index.html.erb
<h1>Listing relatives</h1>

<table>
  <tr>
    <th>Present</th>
    <th>Existing member</th>
    <th>New member</th>
    <th>Relationship</th>
    <th>Flag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relatives.each do |relative| %>
  <tr>
    <td><%= relative.present_id %></td>
    <td><%= relative.existing_member_id %></td>
    <td><%= relative.new_member_id %></td>
    <td><%= relative.relationship %></td>
    <td><%= relative.flag %></td>
    <td><%= link_to 'Show', relative %></td>
    <td><%= link_to 'Edit', edit_relative_path(relative) %></td>
    <td><%= link_to 'Destroy', relative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relative', new_relative_path %>

app/views/relatives/new.html.erb
<h1>New relative</h1>

<%= render 'form' %>

<%= link_to 'Back', relatives_path %>

app/views/relatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Present:</b>
  <%= @relative.present_id %>
</p>

<p>
  <b>Existing member:</b>
  <%= @relative.existing_member_id %>
</p>

<p>
  <b>New member:</b>
  <%= @relative.new_member_id %>
</p>

<p>
  <b>Relationship:</b>
  <%= @relative.relationship %>
</p>

<p>
  <b>Flag:</b>
  <%= @relative.flag %>
</p>


<%= link_to 'Edit', edit_relative_path(@relative) %> |
<%= link_to 'Back', relatives_path %>