config/routes.rb
Mj::Application.routes.draw do


  resources :services


  resources :socials


  resources :gender_notifications


  root :to => redirect('/about')

  get "about/aboutus"

  captcha_route

  resources :posts


  # root :to => "home#index"
  
  # get "home/index"


  # get "home/aboutus"
  # root :to => redirect('/aboutus')

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :videos

 
 
  resources :ads


  resources :relatives
  resources :mappings
  resources :mapping_relations
  resources :feedbacks
  resources :relations
  resources :family_members
  resources :users
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "mjnews" => "posts#index", :as => "posts"



  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "signup" => "users#sign_up", :as => "signup"
  get '/ads/:id/sai', to: 'ads#sai'
  get "search" => "users#index", :as => "search"
  get "log" => "users#search", :as => "log"
  get "slog" => "services#servicelog", :as => "slog"
  get "products" => "ads#products", :as => "products"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "tc" => "home#tc" , :as => "tc"


 
   get "privacy" => "home#privacy" , :as => "privacy"

  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  # get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  # root :to => "users#home" # "advertisements"
  match ':controller(/:action(/:id))(.:format)'
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :content, :title, :youtube
end

app/controllers/videos_controller.rb
 class VideosController < InheritedResources::Base

    before_filter  :required_login, :only => [:show]

  def index
    @video = Video.find(2)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end
  def show
    @videos = Video.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
  def create
    user = User.authenticate(params[:mj_id], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/videos/2", :notice => "Logged in!"
    else
       redirect_to "/videos/2/edit", :notice => "Invalid MJID or password"
    end
  end
end

 
 

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :youtube %><br />
    <%= f.text_field :youtube %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class="row">
<div class="span3"></div>
<div class="span6">
  <div class="" style="width:500px;">
    <form accept-charset="UTF-8"  class="form-centered"  action="/videos" method="post" />
   <legend>Log In</legend>
    <div class="control-group">
      <label for ="mj_id" class="control-label"><b>MJ ID</b></label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-user"></i></span>
          <input type="text" class="input-xlarge" id="mj_id" name="mj_id" required="required" placeholder="MJID">
        </div>
      </div>
    </div>

    <div class="control-group">
      <label for = "password" class="control-label"><b>Password</b></label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-lock"></i></span>
          <input type="password" id="password" class="input-xlarge" name="password" placeholder="Password" required="required">
        </div>
      </div>
    </div>


    <div class="control-group">
      <label class="control-label"></label>
      <div class="controls">
        <button type="submit" name="commit" value="Log in"class="btn btn-success">Login </button>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"></label>
      <div class="controls">
        <p>Forgot your password, <a href="/change_password">Recover it !</a><br></p>
        <p>Are you new to MJ, <a href="/signup">Register here !</a><br></p>
      </div>
    </div>
    </form>
  </div>
</div>
<div class="span3"></div>
</div>
<br><br><br><br><br><br><br><br><br>

app/views/videos/index.html.erb
 <div class="videoback"><br />
<div class="frame"> <iframe width="640" height="360" src="https://www.youtube.com/embed/M3r4gSpmYVA?feature=player_detailpage" frameborder="0" allowfullscreen></iframe></div>
<br>
 <a href = "<%= redirect_to = "/videos/2" %>" class="btn btn-large btn-primary" style="margin-left:523px">Show More ... </a>
<br><br><br>
  <div></div>
<style type="text/css">
.videoback
{
	background-color:#424242  ;
	border-radius: 15px;
	width:1100px;
	height:550px;
}
.frame{
	margin-top: 50px;
	margin-left: 40px;
	text-align:;
}
	</style>

app/views/videos/inx.html.erb
 <head>
  <script src="/assets/video.js"></script>
    <script>
 function popup(pPopup, pYt){ //pYt optional
    $('iframe').attr('src', pYt);
}
       _V_.options.flash.swf = "/assets/video-js.swf"
    </script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js" type="text/javascript"></script>
  
  <link href="http://vjs.zencdn.net/4.1/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.1/video.js"></script>
</head>
      <link href="assets/video-js.css" rel="stylesheet" type="text/css">
  <!-- video.js must be in the <head> for older IEs to work. -->
  <script src="assets/video.js"></script>
    <link href="/assets/video-js.css" rel="stylesheet">
   
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<!-- <table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th class = "success"><% model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><% model_class.human_attribute_name(:youtube_link) %></th>
      <th>Video</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><% link_to video.id, video_path(video) %></td>
        <td><%= video.title %></td>
        <td><%= video.content %></td>
        <td><% video.youtube %></td>
 -->
       <!--   <td> -->
  <% @videos.each do |ad| %>    

  <a href="javascript:void(null)" onclick=<%=video.youtube%> class="more_details">more details</a>
          
                  <% end %>
 
   <iframe width="540" height="320" src=<%=video.content%> frameborder="0" allowfullscreen></iframe> 
 <!-- </td> -->
   <!--  <td><iframe width="640" height="360" src=<%=video.content%> frameborder="0" allowfullscreen></iframe></td>
         <td></td> -->
        <td>
     <!--      <%= link_to t('.edit', :default => t("-helpers.links.edit")),
                      edit_video_path(video), :class => 'btn btn-small' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_path(video),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>   -->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  
<%  link_to t('.new', :default => t("helpers.links.new")),
            new_video_path,
            :class => 'btn btn-primary' %>
    <a href="javascript:void(null)" onclick="popup('popUpDiv', 'http://www.youtube.com/embed/NWHfY_lvKIQ')" class="more_details">more details</a>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<head>
  <link href="http://vjs.zencdn.net/4.1/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.1/video.js"></script>
</head>
      <link href="assets/video-js.css" rel="stylesheet" type="text/css">
  <!-- video.js must be in the <head> for older IEs to work. -->
  <script src="assets/video.js"></script>
    <link href="/assets/video-js.css" rel="stylesheet">
    <script src="/assets/video.js"></script>
    <script>
      _V_.options.flash.swf = "/assets/video-js.swf"
    </script>
<%- model_class = Video -%>
<div class="page-header">
 </div>
  
    <% @videos.each do |video| %>
    <div class="span5">
       <h3 style="color:#890000"><%= video.title %></h3>
         <tr><td>
           <iframe width="380" height="240" src=<%=video.content%> frameborder="0" allowfullscreen></iframe></td></tr>
     </div>
      <% end %>


<div class="span10"> <br /><br />
 
</div>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />