config/routes.rb
Mj::Application.routes.draw do


  resources :services


  resources :socials


  resources :gender_notifications


  root :to => redirect('/about')

  get "about/aboutus"

  captcha_route

  resources :posts


  # root :to => "home#index"
  
  # get "home/index"


  # get "home/aboutus"
  # root :to => redirect('/aboutus')

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :videos

 
 
  resources :ads


  resources :relatives
  resources :mappings
  resources :mapping_relations
  resources :feedbacks
  resources :relations
  resources :family_members
  resources :users
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "mjnews" => "posts#index", :as => "posts"



  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "signup" => "users#sign_up", :as => "signup"
  get '/ads/:id/sai', to: 'ads#sai'
  get "search" => "users#index", :as => "search"
  get "log" => "users#search", :as => "log"
  get "slog" => "services#servicelog", :as => "slog"
  get "products" => "ads#products", :as => "products"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "tc" => "home#tc" , :as => "tc"


 
   get "privacy" => "home#privacy" , :as => "privacy"

  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  # get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  # root :to => "users#home" # "advertisements"
  match ':controller(/:action(/:id))(.:format)'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :details, :user_id
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def index
    @feedbacks = Feedback.all
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def new
    @feedback = Feedback.new
    @user = User.find(params[:id])
    @show_feedback = Feedback.find_all_by_user_id(@user.id)
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.user_id = current_user.id
    @feedback.save
    redirect_to feedbacks_url, notice: 'Feedback was successfully created.'
  end

  def update
    @feedback = Feedback.find(params[:id])
    @feedback.update_attributes(params[:feedback])
    redirect_to feedbacks_url, notice: 'Feedback was successfully updated.'
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    redirect_to feedbacks_url
  end

  def display_feedback
    @user = User.find(params[:id])
    logger.info "feeeeeeeeeeeeeeeeeedddddd #{params[:feedback][:details].inspect}"
    @fed = Feedback.new
    @fed.details = params[:feedback][:details]
    @fed.user_id = @user.id
    @fed.save
    redirect_to "/feedbacks/new/#{current_user.id}", :notice => "Feedback sent."
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details,:style=>"height:150px;width:400px;" %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<% if current_user.user_id == 0 %>
<div>
  <a class="btn btn-danger" href="/users?begin=15">Users</a>
  <a class="btn btn-danger" href="/family_members">Family members</a>
  <a class="btn btn-danger" href="/relations">Relations</a>
  <a class="btn btn-danger" href="/feedbacks">View Feedbacks</a>
  <a class="btn btn-danger" href="/publish_event">Publish Event</a>
</div>
<% else %>
  <div >
  <a class="btn btn-danger" href="/users/edit_profile/<%= current_user.id %>">Profile</a>
  <a class="btn btn-danger" href="/family_members/family/<%= current_user.id %>">Family Tree</a>
  <a class="btn btn-danger" href="/feedbacks">Feedback</a>
  <a class="btn btn-danger" href="/feedbacks/new">Give feedback</a>
</div>  
 




<% end %>
<h2 style="color:#890000">Feedback</h2>

<table>
  <tr>
    <th>MJ ID</th>
    <th>Details</th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.user.mj_id %></td>
    <td><%= feedback.details %></td>
   
  </tr>
<% end %>
</table>

app/views/feedbacks/new.html.erb
<div class="row">
	<div class="span6">
		<div>
			<a class="btn btn-danger" href="/users/edit_profile/<%= current_user.id %>">Profile</a>
			<a class="btn btn-danger" href="/family_members/family/<%= current_user.id %>">Family Tree</a>
			<a class="btn btn-danger" href="/feedbacks/new/<%= current_user.id %>">Give feedback</a>
		</div>
		<h2 style="color:#890000">Give your feedback</h2>
		<form accept-charset="UTF-8" action="/feedbacks/display_feedback/<%= current_user.id %>"class="new_feedback" id="new_feedback" method="post">
			<div style="margin:0;padding:0;display:inline">
				<input name="utf8" type="hidden" value="&#x2713;" />
				<input name="authenticity_token" type="hidden" value="0QBdPSOO/IsWJsZO2BpIXY8FVGSBZg6jdyHZGTZ1qbY=" />
			</div>
			<div class="field">
	    		<label for="feedback_details">Details</label>
	    		<textarea cols="40" id="feedback_details" name="feedback[details]" rows="20" 		style="height:150px;width:400px;">
				</textarea>
	 		</div>
			<br/>
	  		<div class="actions">
	    		<input class="btn btn-success" name="commit" type="submit" value="Create Feedback" />
			</div>
		</form>
	</div>
	<div class="span6">
		<table class="table table-striped table-bordered table-condensed table-hover">
		    <tr>
		        <th><center>Details</center></th>
		        <th><center>mjid</center></th>
		   	    <th><center>Created_at</center></th>
		    </tr>
		   	<% @show_feedback.each do |x| %>
		    <tr>
		    	<td width="65%"><%= x.details %></td>
		    	  	<td width="35%"><%= x.user.mj_id %></td>
		    	<td width="45%"><%= x.created_at %></td>

		    </tr></br>
			<% end %>
		</table>
	</div>
</div>
<br><br><br><br><br><br><br><br><br>		
		 

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Details:</b>
  <%= @feedback.details %>
</p>

<p>
  <b>User:</b>
  <%= @feedback.user_id %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>