config/routes.rb
Mj::Application.routes.draw do


  resources :services


  resources :socials


  resources :gender_notifications


  root :to => redirect('/about')

  get "about/aboutus"

  captcha_route

  resources :posts


  # root :to => "home#index"
  
  # get "home/index"


  # get "home/aboutus"
  # root :to => redirect('/aboutus')

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :videos

 
 
  resources :ads


  resources :relatives
  resources :mappings
  resources :mapping_relations
  resources :feedbacks
  resources :relations
  resources :family_members
  resources :users
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "mjnews" => "posts#index", :as => "posts"



  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "signup" => "users#sign_up", :as => "signup"
  get '/ads/:id/sai', to: 'ads#sai'
  get "search" => "users#index", :as => "search"
  get "log" => "users#search", :as => "log"
  get "slog" => "services#servicelog", :as => "slog"
  get "products" => "ads#products", :as => "products"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "tc" => "home#tc" , :as => "tc"


 
   get "privacy" => "home#privacy" , :as => "privacy"

  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "aboutus" => "home#aboutus", :as => "aboutus"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  # get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  # root :to => "users#home" # "advertisements"
  match ':controller(/:action(/:id))(.:format)'
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
  attr_accessible :first_person, :relationship, :second_person
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  # GET /mappings
  # GET /mappings.json
  def index
    @mappings = Mapping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mappings }
    end
  end

  # GET /mappings/1
  # GET /mappings/1.json
  def show
    @mapping = Mapping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mapping }
    end
  end

  # GET /mappings/new
  # GET /mappings/new.json
  def new
    @mapping = Mapping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mapping }
    end
  end

  # GET /mappings/1/edit
  def edit
    @mapping = Mapping.find(params[:id])
  end

  # POST /mappings
  # POST /mappings.json
  def create
    @mapping = Mapping.new(params[:mapping])

    respond_to do |format|
      if @mapping.save
        format.html { redirect_to @mapping, notice: 'Mapping was successfully created.' }
        format.json { render json: @mapping, status: :created, location: @mapping }
      else
        format.html { render action: "new" }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mappings/1
  # PUT /mappings/1.json
  def update
    @mapping = Mapping.find(params[:id])

    respond_to do |format|
      if @mapping.update_attributes(params[:mapping])
        format.html { redirect_to @mapping, notice: 'Mapping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings/1
  # DELETE /mappings/1.json
  def destroy
    @mapping = Mapping.find(params[:id])
    @mapping.destroy

    respond_to do |format|
      format.html { redirect_to mappings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/views/mappings/_form.html.erb
<%= form_for(@mapping) do |f| %>
  <% if @mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mapping.errors.count, "error") %> prohibited this mapping from being saved:</h2>

      <ul>
      <% @mapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_person %><br />
    <%= f.text_field :first_person %>
  </div>
  <div class="field">
    <%= f.label :second_person %><br />
    <%= f.text_field :second_person %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.text_field :relationship %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mappings/edit.html.erb
<h1>Editing mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @mapping %> |
<%= link_to 'Back', mappings_path %>

app/views/mappings/index.html.erb
<h1>Listing mappings</h1>

<table>
  <tr>
    <th>First person</th>
    <th>Second person</th>
    <th>Relationship</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mappings.each do |mapping| %>
  <tr>
    <td><%= mapping.first_person %></td>
    <td><%= mapping.second_person %></td>
    <td><%= mapping.relationship %></td>
    <td><%= link_to 'Show', mapping %></td>
    <td><%= link_to 'Edit', edit_mapping_path(mapping) %></td>
    <td><%= link_to 'Destroy', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mapping', new_mapping_path %>

app/views/mappings/new.html.erb
<h1>New mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', mappings_path %>

app/views/mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First person:</b>
  <%= @mapping.first_person %>
</p>

<p>
  <b>Second person:</b>
  <%= @mapping.second_person %>
</p>

<p>
  <b>Relationship:</b>
  <%= @mapping.relationship %>
</p>


<%= link_to 'Edit', edit_mapping_path(@mapping) %> |
<%= link_to 'Back', mappings_path %>